apiVersion: v1
kind: Service
metadata:
  name: apigateway
spec:
  selector:
    app: backend
  ports:
    - name: api
      port: 8000
      targetPort: 8000
    - name: advisorservice
      port: 8100
      targetPort: 8100

    - name: eureka
      port: 8761
      targetPort: 8761

