variables:
  DOCKER_DRIVER: overlay

stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-job:      # This job runs in the deploy stage.
  image: docker:latest
  stage: build  # It only runs when *both* jobs in the test stage complete successfully.
  services:
    - name: docker:dind
  script:
    - echo "Deploying application..."
    - docker build -t registry.gitlab.com/arctic-monkeys/markmyflow . -f Dockerfile
    - echo "Login to gitlab..."
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - echo "Pushing to gitlab..."
    - docker push registry.gitlab.com/arctic-monkeys/markmyflow
    - echo "Application successfully deployed."
  
deployjob:
  stage: deploy 
  image:
    name: mcr.microsoft.com/azure-cli:latest
    entrypoint: ['']
  script:
    - az login --service-principal --username 8ec69190-1f73-42f9-b6b6-058cb18a02bb --password bGV8Q~a3v6UGLLkBoGS8cW1LbGAutdFkvKo6wa-. --tenant 68f49f00-0be1-4a71-b9c4-3ad121be1108
    - az account set --subscription a2f1143f-5e9c-4440-bd9f-44393e9644d0
    - az aks get-credentials --resource-group Pidev --name test
    - curl -LO https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl
    - chmod +x kubectl
    - mv kubectl /usr/local/bin/
    - kubectl rollout restart deployment/frontend 
